### ISSUE TITLE
add slides from January meetup

### ISSUE THREAD

**Issue by monicagerber** [rladies-seattle/blogdown_site#7]
@katiejolly - i will add you to our google drive folder too (where you can save slides)

Let me know if you're comfortable with figuring out how to add.

**Comment by ivelasq** [comment]
I added some links: https://rladiesseattle.org/projects/
Let me know if anything is missing!

**Comment by monicagerber** [comment]
Looks good, thanks @ivelasq !

**Comment by ivelasq** [comment]
Great! Closing, but let me know if I missed anything :)
